// src/components/blog-posts.svelte
<script>
  import { format, parseISO } from "date-fns";
  export let blogPosts;
  export let blogBaseUrl;
</script>

<div
  class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 items-center justify-center mx-4 mt-8"
>
  {#each blogPosts as post}
    <a
      href={`${blogBaseUrl}${post.slug}`}
      class="flex justify-center items-center focus:ring focus:outline-none p-4"
    >
      <div
        class="bg-secondary rounded-xl shadow-md shadow-secondary p-4 hover:shadow-lg hover:shadow-accent transition duration-150 ease-out w-auto h-auto md:w-96 md:h-96"
      >
        <img
          src={post.coverImage}
          alt={post.title}
          class="rounded-2xl shadow-md"
        />
        <h2 class="mt-4 text-xl font-bold text-white text-center md:text-left">
          {post.title}
        </h2>
        <h3 class="mt-2 text-gray-300 text-lg text-center md:text-left">
          {format(parseISO(post.dateAdded), "PPP")}
        </h3>
      </div>
    </a>
  {/each}
</div>

// components/Home/BlogPosts/BlogPosts.tsx
import BlogPostCard from "@/components/Blog/BlogPostCard";
import Link from "@/components/Shared/Link";
import { ArrowRight } from "react-feather";
import { HashnodePostWithPlaceHolderImage } from "types/hashnode";

interface BlogPostsProps {
  posts: HashnodePostWithPlaceHolderImage[];
  domain: string;
}

const BlogPosts = ({ posts, domain }: BlogPostsProps): JSX.Element => {
  return (
    <>
      <h2 className="mb-8 text-3xl font-bold">Blog Posts</h2>
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {posts.slice(0, 4).map(post => (
          <BlogPostCard
            key={post._id}
            title={post.title}
            image={post.coverImage}
            placeholderImage={post.placeholderImage}
            date={post.dateAdded}
            readingTime={post.readingTime.text}
            url={`https://${domain}/${post.slug}`}
          />
        ))}
      </div>
      <Link
        href="/blog"
        className="group mt-8 flex items-center justify-start space-x-2 text-xl font-medium"
      >
        <span>View All Blog Posts</span>
        <ArrowRight className="h-4 w-4 transition duration-200 group-hover:translate-x-1" />
      </Link>
    </>
  );
};

export default BlogPosts;
