// src/components/projects.svelte
<script>
  import Icon from "./icons/index.svelte";
  export let projects;
</script>

<div
  id="projects"
  class="mt-8 mx-8 md:mt-16 lg:mt-32 md:mx-24 lg:mx-32 xl:mx-40"
>
  <h2
    class="text-accent text-5xl md:text-6xl font-bold mb-8 text-center lg:text-left"
  >
    Projects
  </h2>
  {#each projects as project}
    <div
      class="flex flex-col justify-center items-center lg:items-stretch lg:flex-row "
    >
      <picture class="w-11/12 md:w-1/2">
        <source
          media="(min-width: 1024px)"
          srcset={`https://ctohm-edge-resizer.anishde12020.workers.dev/vw=0.6_output=auto/${
            new URL(project.image).hostname
          }${new URL(project.image).pathname}`}
        />
        <source
          media="(min-width: 768px)"
          srcset={`https://ctohm-edge-resizer.anishde12020.workers.dev/vw=0.8_output=auto/${
            new URL(project.image).hostname
          }${new URL(project.image).pathname}`}
        />
        <source
          srcset={`https://ctohm-edge-resizer.anishde12020.workers.dev/vw=0.8_output=auto/${
            new URL(project.image).hostname
          }${new URL(project.image).pathname}`}
        />
        <img
          src={`https://ctohm-edge-resizer.anishde12020.workers.dev/output=auto/${
            new URL(project.image).hostname
          }${new URL(project.image).pathname}`}
          class="rounded-xl"
          alt={project.name}
        />
      </picture>
      <div
        class="flex flex-col justify-center items-center lg:justify-between lg:items-start mt-8 lg:mt-0 lg:ml-16"
      >
        <div
          class="flex flex-col justify-center items-center lg:justify-left lg:items-start"
        >
          <h3 class="text-5xl md:text-6xl lg:text-7xl	 font-bold text-white">
            {project.name}
          </h3>
          <p
            class="text-gray-300 font-semibold text-xl md:text-2xl lg:text-3xl mt-2 md:mt-4 xl:mt-8 text-center lg:text-left"
          >
            {project.description}
          </p>
        </div>
        <div
          class="flex flex-col justify-center items-center lg:items-start lg:justify-start mt-8 lg:mt-0"
        >
          <a
            href={project.url}
            class="text-gray-100 hover:text-accent transition dureation-300 text-md md:text-lg lg:text-xl text-center lg:text-left mb-4"
          >
            <div class="flex">
              <Icon iconName="link" className="w-6 h-6 mr-2 lg:mr-4" />
              <span>{project.url}</span>
            </div>
          </a>

          <a
            href={project.github}
            class="text-gray-100 hover:text-accent transition dureation-300 text-md md:text-lg lg:text-xl text-center lg:text-left"
          >
            <div class="flex">
              <Icon iconName="github" className="w-6 h-6 mr-2 lg:mr-4" />
              <span>{project.github.slice(19)}</span>
            </div>
          </a>
        </div>
      </div>
    </div>
  {/each}
</div>

// components/Home/Projects/Projects.tsx
import { allProjects } from ".contentlayer/generated";
import Link from "@/components/Shared/Link";
import { ArrowRight } from "react-feather";

const Projects = (): JSX.Element => {
  return (
    <div className="my-16 flex flex-col">
      <h2 className="mb-8 text-3xl font-bold">Projects</h2>
      <div className="flex flex-col space-y-8">
        {allProjects.slice(0, 2).map(project => (
          <Link
            key={project._id}
            href={`/projects/${project.slug}`}
            className="group ml-4 flex flex-col space-y-2"
          >
            <h3 className="flex flex-row items-center space-x-2 text-lg font-semibold">
              <span>{project.name}</span>{" "}
              <ArrowRight className="h-4 w-4 translate-x-0 transition duration-200 group-hover:translate-x-1" />
            </h3>
            <p className="text-md text-gray-300">{project.description}</p>
          </Link>
        ))}
      </div>
      <Link
        href="/projects"
        className="group mt-8 flex items-center justify-start space-x-2 text-xl font-medium"
      >
        <span>View All Projects</span>
        <ArrowRight className="h-4 w-4 transition duration-200 group-hover:translate-x-1" />
      </Link>
    </div>
  );
};

export default Projects;
