// components/Common/Footer/Footer.tsx
import Link from "@/components/Shared/Link";
import Socials from "@/components/Shared/Socials";

const Footer = (): JSX.Element => {
  return (
    <footer className="mx-auto mb-16 flex max-w-3xl flex-col items-center space-y-4 px-8 text-center">
      <Socials small className="mb-8" />
      <p>
        Made by <Link href="https://twitter.com/AnishDe12020">Anish De</Link>
      </p>
      <p>
        This portfolio is open source and the source code can be found{" "}
        <Link href="https://github.com/AnishDe12020/portfolio">on GitHub</Link>
      </p>
    </footer>
  );
};

export default Footer;

// src/components/footer.svelte
<div class="flex flex-col justify-center items-center mt-16 mb-8 text-white">
  <p>
    Made by <a
      href="https://twitter.com/AnishDe12020"
      class="text-accent hover:opacity-30 transition duration-200">Anish De</a
    >
  </p>
  <p class="mt-4">
    Check out the <a
      href="https://github.com/AnishDe12020/portfolio"
      class="text-accent hover:opacity-30 transition duration-200"
      >source code</a
    >
  </p>
</div>
