// src/routes/__error.svelte
<div
  class="w-screen flex flex-col space-y-8 justify-center items-center text-gray-100"
>
  <h1 class="text-9xl text-accent font-serif">404</h1>
  <p class="text-4xl">This page doesn't exist</p>
  <a
    href="/"
    class="border-accent border-2 text-accent rounded-2xl px-4 py-2 hover:bg-accent hover:text-secondary transition duration-200 text-xl"
    >Go back to the homepage</a
  >
</div>

// pages/_error.tsx
import Link from "@/components/Shared/Link";

function Error({ statusCode }) {
  return (
    <div className="mt-16 mb-96 flex flex-col items-center justify-center">
      {statusCode ? (
        <h1 className="text-center text-6xl font-bold">
          {statusCode}
          {statusCode === 404
            ? " Page Not Found"
            : statusCode === 500
            ? " Server Error"
            : ""}
        </h1>
      ) : (
        <h1 className="text-center text-6xl font-bold">
          A client side error occured.
        </h1>
      )}
      <Link
        noHighlight
        noExternalLinkIcon
        noGradientUnderline
        href="/"
        className="my-16 rounded-lg border-[1px] border-tertiary bg-secondary px-4 py-2"
      >
        Go Home
      </Link>
    </div>
  );
}

Error.getInitialProps = ({ res, err }) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404;
  return { statusCode };
};

export default Error;
